db:
  image: mongo
  ports:
    - "27017:27017"
  volumes :
    - /root/data
  command: "--smallfiles --logpath=/dev/null"
  environment: 
        MONGODB_USER: "admin"
        MONGODB_PASS: "admin"
bot:
  build: .
  command: npm start
  links:
    - db
